name: life
favicon: null
layout_spectrum: 0.9791522382292897
typography_spectrum: 0.09620808041654527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2574094219598919
  lightness: 0.5063998713158071
  saturation: 0.39895646437071264
  rhythmicContrast: 0.2696428631898016
purpose: []
